<div class="page-header">
    <h1><?= $this->title ?></h1>
</div>
<?= $this->literal(array('tag' => 'div', 'class' => 'content')) ?>

<?php
     $target = new OntoWiki_Url(
         array(
             'controller' => 'linghub',
             'action' => 'adddataset'
         )
     );
?>

<form id="datasetForm" method="post" class="form-inline" target="<?= $target ?>" >
<div class="row">
  <div class="col-lg-6">
  <label class="control-label" for="datasetUri">Dataset URI</label>
    <div class="input-group">
      <input type="url" class="form-control" id="datasetUri" name="datasetUri" placeholder="Please enter your dataset URI here" />
      <span class="input-group-btn">
        <button id="registerButton" class="btn btn-default" type="submit">Register/Update</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
</form>

<div id="result">
</div>
<script type="text/javascript">
    $('#datasetForm').submit(
        function(event) {
            $('#result').spin();
            var formData = $('#datasetForm').serializeArray();
            $.post(
                '<?= $target ?>',
                formData,
                function(data) {
                    var data = JSON.parse(data);
                    if (data.type == 'data') {
                        $('#result').html('<dl id="definitionList" class="dl-horizontal"></dl>');
                        $.each(data.content[formData[0].value], function(k,v) {
                            var title = data.titles[k];
                            var property = '<dt>' + title + '</dt>';
                            for (var i in v) {
                                property += '<dd>' + v[i].value + '</dd>';
                            }
                            $('#definitionList').append(property);
                        });
                    } else {
                        var errorMessage;
                        if (data.type == 'error') {
                            errorMessage = 'The result is not in the correct format.';
                        } else {
                            errorMessage = data.message;
                        }

                        $('#result').html('<div class="alert alert-danger">' + errorMessage + '</div>');
                    }
               }
            );
            event.preventDefault();
        }
    );
</script>

<?php
// uses default content properties
//echo $this->literal(array('tag' => 'div', 'class' => 'content'));
?>
