<div class="page-header">
    <h1><?= $this->title ?></h1>
</div>
<?= $this->literal(array('tag' => 'div', 'class' => 'content')) ?>

<?php
     $target = new OntoWiki_Url(
         array(
             'controller' => 'linghub',
             'action' => 'adddataset'
         )
     );
?>

<form id="datasetForm" method="post" class="form-inline" target="<?= $target ?>" >
<div class="row">
  <div class="col-lg-6">
  <label class="control-label" for="datasetUri">Dataset URI</label>
    <div class="input-group">
      <input type="url" class="form-control" id="datasetUri" name="datasetUri" placeholder="Please enter your dataset URI here" />
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Register/Update</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
</form>


<div id="resultList">
</div>
<script type="text/javascript">
    $("#datasetForm").submit(
        function(event) {
            alert("form wurde abgeschickt");
            $.post(
                "<?= $target ?>",
                $("#datasetForm").serializeArray(),
                function(data) {
                    $("#resultList").html(data);
               }
            );
            event.preventDefault();
        }
    );
</script>

<?php
// uses default content properties
//echo $this->literal(array('tag' => 'div', 'class' => 'content'));
?>
