<?php
$titleSubject = '&lt;' . $this->resourceUri . '&gt;';
if (substr($this->title, 0, 2) == 'ns' || $this->title == $this->resourceUri) {
    $this->title = $titleSubject;
    $titleSubject = '';
}
?>
<div class="page-header">
    <h1><?= $this->title ?>
        <small><?= $titleSubject ?> a <span title="http://www.w3.org/ns/sparql-service-description#Service">sd:Service</span></small>
    </h1>
</div>

<div class="row">
    <div class="col-md-8">
        <a href="<?= $this->resourceUri ?>"><button type="button" class="btn btn-default" >Go to endpoint</button></a>
        <a href="<?= $this->Url(array('uri' => $this->resourceUri, 'stayOnSite' => false)) ?>"><button type="button" class="btn btn-default" >Show resource in OntoWiki</button></a>
        <a href=""><button type="button" class="btn btn-default" title="Request this resource to be added to the update queue">Update</button></a>
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Export … <span class="caret"></span></button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="<?= $this->Url(array('uri' => $this->resourceUri, 'c' => 'resource', 'a' => 'export'), array('f' => 'turtle')) ?>">as Turtle</a></li>
                <li><a href="<?= $this->Url(array('uri' => $this->resourceUri, 'c' => 'resource', 'a' => 'export'), array('f' => 'rdfxml')) ?>">as RDF/XML</a></li>
                <li><a href="<?= $this->Url(array('uri' => $this->resourceUri, 'c' => 'resource', 'a' => 'export'), array('f' => 'rdfjson')) ?>">as RDF/Json (Talis)</a></li>
                <li><a href="<?= $this->Url(array('uri' => $this->resourceUri, 'c' => 'resource', 'a' => 'export'), array('f' => 'rdfn3')) ?>">as Notation 3</a></li>
            </ul>
        </div>


        <h2>Datasets <small>This endpoint provides access to the following datasets</small></h2>
            <p>The endpoint provides access to <?= $this->literal(array('property' => 'voidx:datasetCount')) ?> dataset(s).</p>
            <?php
                $count = $this->count(array('where' => '{<' . $this->resourceUri . '> voidx:providesAccessTo ?resourceUri } union {<' . $this->resourceUri . '> sd:defaultDataset ?resourceUri }'));
                if ($count > 0) {
                    echo $this->query(
                        array(
                            'where' => '{<' . $this->resourceUri . '> voidx:providesAccessTo ?resourceUri } union {<' . $this->resourceUri . '> sd:defaultDataset ?resourceUri }',
                            'template' => 'dataset',
                            'limit' => 10,
                            'active' => $this->literal(array('property' => 'sd:defaultDataset', 'plain' => 'true')),
                            'prefix' => '<ul class="list-unstyled">',
                            'suffix' => '</ul>',
                        )
                    );
                    if ($count > 10) {
                        echo 'and more …';
                    }
                } else {
                    echo 'No datasets found';
                }
            ?>
        <h2>Data Level metadata</h2>
        <dl class="dl-horizontal">
            <?= $this->literal(array('property' => 'void:triples', 'prefix' => '<dt>Triples</dt><dd>', 'suffix' => '</dd>')); ?>
            <?= $this->literal(array('property' => 'void:entities', 'prefix' => '<dt>Entities</dt><dd>', 'suffix' => '</dd>')); ?>
            <?= $this->literal(array('property' => 'void:classes', 'prefix' => '<dt>Classes</dt><dd>', 'suffix' => '</dd>')); ?>
            <?= $this->literal(array('property' => 'void:properties', 'prefix' => '<dt>Properties</dt><dd>', 'suffix' => '</dd>')); ?>
            <?= $this->literal(array('property' => 'void:distinctSubjects', 'prefix' => '<dt>Distinct subjects</dt><dd>', 'suffix' => '</dd>')); ?>
            <?= $this->literal(array('property' => 'void:distinctObjects', 'prefix' => '<dt>Distinct objects</dt><dd>', 'suffix' => '</dd>')); ?>
        </dl>
        <h3>Triple structure</h3>
                <script language="javascript">
                var browser = new StructureBrowser(
                    '<?= $this->resourceUri ?>',
                    '<?= $this->url(array('c' => 'structurebrowser', 'a' => 'browse'), array('resourceUri' => $this->resourceUri)) ?>'
                );
        </script>
        <button onClick="browser.draw($('#structure-browser-button'))" id="structure-browser-button" type="button" class="btn btn-default" >Start structure browser</button>
        <h2>Debug <small>Exceptions and other information that occured when querying the endpoint</small></h2>
        <?= $this->literal(array('property' => 'rdfs:comment', 'tag' => 'div', 'class' => 'bs-callout bs-callout-info')) ?>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Service Level metadata</h3>
            </div>
            <div class="panel-body" id="infoBoxList">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th class="col-md-4"><span class="glyphicon glyphicon-stats"></span> Status</th>
                            <td><?php
                                    $string = $this->query(
                                        array(
                                            'where' => '<' . $this->resourceUri . '> ends:status ?resourceUri. optional {?resourceUri dct:date ?date}',
                                            'template' => 'endpointstatus',
                                            'orderby' => 'desc(?date)',
                                            'limit' => 1
                                        )
                                    );
                                    if (empty($string)) {
                                        echo 'n/a';
                                    } else {
                                        echo $string;
                                    }
                                ?></td>
                        </tr>
                        <tr>
                            <th><span class="glyphicon glyphicon-pencil"></span> Supported language</th>
                            <td><?php
                                    $string = $this->query(
                                        array(
                                            'where' => '<' . $this->resourceUri . '> sd:supportedLanguage ?resourceUri',
                                            'template' => 'liplain',
                                        )
                                    );
                                    if (empty($string)) {
                                        echo 'n/a';
                                    } else {
                                        echo $string;
                                    }
                                ?></td>
                        </tr>
                        <tr>
                            <th><span class="glyphicon glyphicon-cog"></span> Features</th>
                            <td><?php
                                    $string = $this->query(
                                        array(
                                            'where' => '<' . $this->resourceUri . '> sd:feature ?resourceUri',
                                            'template' => 'liplain',
                                        )
                                    );
                                    if (empty($string)) {
                                        echo 'n/a';
                                    } else {
                                        echo $string;
                                    }
                                ?></td>
                        </tr>
                        <tr>
                            <th><span class="glyphicon glyphicon-file"></span> Result formats</th>
                            <td><?php
                                    $string = $this->query(
                                        array(
                                            'where' => '<' . $this->resourceUri . '> sd:resultFormat ?resourceUri',
                                            'template' => 'liplain',
                                        )
                                    );
                                    if (empty($string)) {
                                        echo 'n/a';
                                    } else {
                                        echo $string;
                                    }
                                ?></td>
                        </tr>
                        <tr>
                            <th><span class="glyphicon glyphicon-cloud"></span> external links</th>
                            <td><?php
                                    $string = $this->query(
                                        array(
                                            'where' => '<' . $this->resourceUri . '> rdfs:seeAlso ?resourceUri',
                                            'template' => 'liplain',
                                        )
                                    );
                                    if (empty($string)) {
                                        echo 'n/a';
                                    } else {
                                        echo $string;
                                    }
                                ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


<?php
