<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * querylist li plain element template
 *
 * this template is used in combination with the querylist helper to render
 * lists of resources which match a given SPARQL query
 *
 * TODO: make more independend from the query (e.g. take the first projection variable)
 */

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;


// if we have a literal item, do not do anything but an li item
if (!Erfurt_Uri::check($resourceUri)) {
    echo 'no status information available';
} else {
    $date = $this->literal(array('property' => 'dct:date', 'plain' => true));
    $availability = $this->literal(array('property' => 'ends:statusIsAvailable', 'plain' => true));
    $responseCode = $this->literal(array('property' => 'voidx:httpReturnCode', 'plain' => true));
    if ($availability) {
        $label = 'label-success';
        $icon = 'glyphicon-ok';
        $text = 'available';
    } else {
        $label = 'label-danger';
        $icon = 'glyphicon-remove';
        $text = 'not responding';
    }
    echo '<span class="label ' . $label . '">' . PHP_EOL;
    echo '<span class="glyphicon ' . $icon . '"></span>' . PHP_EOL;
    echo $text . '</span>' . PHP_EOL;
    if (!$availability && !empty($responseCode)) {
        echo 'HTTP code: ' . $responseCode;
    }
    if (!empty($date)) {
        echo '(' . $date . ')';
    }
?>
<?php

}
